### ISSUE TITLE
Plugin does not support Agent/Extended Read

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/extended-read-permission-plugin#12]
https://github.com/jenkinsci/extended-read-permission-plugin/blob/master/src/main/java/hudson/plugins/extendedread/ExtendedReadPermissionEnabler.java does not enable https://github.com/jenkinsci/jenkins/blob/6fb8b93a157e00ac4c057013717e2fef6df1dd09/core/src/main/java/hudson/model/Computer.java#L1800

**Comment by oleg-nenashev** [comment]
We could definitely add one. Does this permission have reasonable test coverage in the Jenkins core? I have never seen it to be used in practice

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/jenkins/pull/4531 adds UI support, so far it seems to only have governed access to `config.xml` (via HTTP or CLI) and the agent log.

**Comment by timja** [comment]
I was planning to send a PR here once https://github.com/jenkinsci/jenkins/pull/4531 is merged, without that PR it really doesn't do anything, so I didn't see the need to add support here yet
