### ISSUE TITLE
parseerror on config.xml

### ISSUE THREAD

**Issue by fenchu** [jenkinsci/extended-read-permission-plugin#16]
### Version report

Jenkins and plugins versions report:

```
* org.jenkins-ci.main:jenkins-war:2.318 
* extended-read-permission - 3.2

```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
ubuntu20.04LTS
```

### Reproduction steps

I can go to any job in jenkins 2.318 and I get either nothing or this error:

### Results

Expected result:

I would have expected to see the config.xml for the job

Actual result:

![jenkins-config xml](https://user-images.githubusercontent.com/11349883/139405166-66dbadeb-6eb7-45d6-a583-476fabee0fca.jpg)

**Comment by daniel-beck** [comment]
This is a limitation of your browser that doesn't support XML 1.1.

Press Cmd-U or equivalent to view the raw source.

**Comment by fenchu** [comment]
Thanks, so the plug in needs a simple update. It is still v3. 2.

**Comment by daniel-beck** [comment]
This has nothing to do with Jenkins. Your web browser does not support the XML version used by Jenkins.
